## numpy_assignment

### 1 : Creating a 1D NumPyArray

We form a 1D NumPy array of integers from 1 to 20 with `np.arange()`. Next, we compute simple statistical values such as sum, mean, median, and standard deviation. We also find the indices of elements greater than 10 using a condition within `np.where()`.

In [19]:
import numpy as np
arr1d = np.arange(1, 21)
print("Sum:", arr1d.sum())
print("Mean:", arr1d.mean())
print("Median:", np.median(arr1d))
print("Std Dev:", arr1d.std())
print("Indices > 10:", np.where(arr1d > 10)[0])



Sum: 210
Mean: 10.5
Median: 10.5
Std Dev: 5.766281297335398
Indices > 10: [10 11 12 13 14 15 16 17 18 19]


### 2 : Creating a 2D Array(4x4)

We create a 2D array of shape 4x4 with numbers from 1 to 16 with `reshape()`. We print the initial array, its transpose with `.T`, and calculate row and column sums.


In [13]:
arr2d = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr2d)
print("Transpose:\n", arr2d.T)
print("Row-wise sum:", arr2d.sum(axis=1))
print("Column-wise sum:", arr2d.sum(axis=0))


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


### 3 : Random 3x3 Arrays – Element-wise and Dot Product

We generate two random 3x3 arrays with integers between 1 and 20 using `np.random.randint()`. Then, we perform element-wise addition, subtraction, and multiplication. Finally, we calculate the dot product using `np.dot()`.

In [7]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Dot Product:\n", np.dot(a, b))


Addition:
 [[32 17 17]
 [23 32 24]
 [33 27 16]]
Subtraction:
 [[  8   1   1]
 [ 15  -8  14]
 [  5  13 -12]]
Multiplication:
 [[240  72  72]
 [ 76 240  95]
 [266 140  28]]
Dot Product:
 [[402 403 331]
 [542 525 478]
 [336 566 280]]


### 4 : Reshaping and Slicing
We reshape a 1D array of size 12 into a 3x4 matrix using `.reshape()`. Then, we extract the first two rows and the last two columns using array slicing.

In [24]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)
print("Sliced:\n", reshaped[:2, -2:])


Sliced:
 [[3 4]
 [7 8]]
